/**
 * Client automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */


using System.Collections.Generic;
using System.Text.Json;
using System.Threading.Tasks;
using RestSharp;
using Sdkgen.Client;
using Sdkgen.Client.Credentials;
using Sdkgen.Client.Exception;

namespace SdkFabric.Starwars;

public class Client : ClientAbstract
{
    public Client(string baseUrl, ICredentials credentials) : base(baseUrl, credentials)
    {
    }

    public PeopleTag People()
    {
        return new PeopleTag(
            this.HttpClient,
            this.Parser
        );
    }

    public FilmTag Film()
    {
        return new FilmTag(
            this.HttpClient,
            this.Parser
        );
    }

    public StarshipTag Starship()
    {
        return new StarshipTag(
            this.HttpClient,
            this.Parser
        );
    }

    public VehicleTag Vehicle()
    {
        return new VehicleTag(
            this.HttpClient,
            this.Parser
        );
    }

    public SpecieTag Specie()
    {
        return new SpecieTag(
            this.HttpClient,
            this.Parser
        );
    }

    public PlanetTag Planet()
    {
        return new PlanetTag(
            this.HttpClient,
            this.Parser
        );
    }



    public static Client Build(ICredentials credentials)
    {
        return new Client("https://swapi.dev/api", credentials);
    }
}
