/**
 * FilmCollection automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;
namespace SdkFabric.Starwars;
public class FilmCollection : Collection
{
    [JsonPropertyName("results")]
    public List<Film>? Results { get; set; }
}
