/**
 * People automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace SdkFabric.Starwars;

/// <summary>
/// A People is an individual person or character within the Star Wars universe
/// </summary>
public class People
{
    [JsonPropertyName("name")]
    public string? Name { get; set; }

    [JsonPropertyName("birth_year")]
    public string? BirthYear { get; set; }

    [JsonPropertyName("eye_color")]
    public string? EyeColor { get; set; }

    [JsonPropertyName("gender")]
    public string? Gender { get; set; }

    [JsonPropertyName("hair_color")]
    public string? HairColor { get; set; }

    [JsonPropertyName("height")]
    public string? Height { get; set; }

    [JsonPropertyName("mass")]
    public string? Mass { get; set; }

    [JsonPropertyName("skin_color")]
    public string? SkinColor { get; set; }

    [JsonPropertyName("homeworld")]
    public string? Homeworld { get; set; }

    [JsonPropertyName("films")]
    public System.Collections.Generic.List<string>? Films { get; set; }

    [JsonPropertyName("species")]
    public System.Collections.Generic.List<string>? Species { get; set; }

    [JsonPropertyName("starships")]
    public System.Collections.Generic.List<string>? Starships { get; set; }

    [JsonPropertyName("vehicles")]
    public System.Collections.Generic.List<string>? Vehicles { get; set; }

    [JsonPropertyName("url")]
    public string? Url { get; set; }

    [JsonPropertyName("created")]
    public System.DateTime? Created { get; set; }

    [JsonPropertyName("edited")]
    public System.DateTime? Edited { get; set; }

}

