/**
 * Planet automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace SdkFabric.Starwars;

/// <summary>
/// A Planet is a large mass, planet or planetoid in the Star Wars Universe, at the time of 0 ABY
/// </summary>
public class Planet
{
    [JsonPropertyName("name")]
    public string? Name { get; set; }

    [JsonPropertyName("diameter")]
    public string? Diameter { get; set; }

    [JsonPropertyName("rotation_period")]
    public string? RotationPeriod { get; set; }

    [JsonPropertyName("orbital_period")]
    public string? OrbitalPeriod { get; set; }

    [JsonPropertyName("gravity")]
    public string? Gravity { get; set; }

    [JsonPropertyName("population")]
    public string? Population { get; set; }

    [JsonPropertyName("climate")]
    public string? Climate { get; set; }

    [JsonPropertyName("terrain")]
    public string? Terrain { get; set; }

    [JsonPropertyName("surface_water")]
    public string? SurfaceWater { get; set; }

    [JsonPropertyName("residents")]
    public System.Collections.Generic.List<string>? Residents { get; set; }

    [JsonPropertyName("films")]
    public System.Collections.Generic.List<string>? Films { get; set; }

    [JsonPropertyName("url")]
    public string? Url { get; set; }

    [JsonPropertyName("created")]
    public System.DateTime? Created { get; set; }

    [JsonPropertyName("edited")]
    public System.DateTime? Edited { get; set; }

}

