/**
 * PlanetCollection automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;
namespace SdkFabric.Starwars;
public class PlanetCollection : Collection
{
    [JsonPropertyName("results")]
    public List<Planet>? Results { get; set; }
}
