/**
 * Root automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;
namespace SdkFabric.Starwars;
public class Root
{
    [JsonPropertyName("films")]
    public string? Films { get; set; }
    [JsonPropertyName("people")]
    public string? People { get; set; }
    [JsonPropertyName("planets")]
    public string? Planets { get; set; }
    [JsonPropertyName("species")]
    public string? Species { get; set; }
    [JsonPropertyName("starships")]
    public string? Starships { get; set; }
    [JsonPropertyName("vehicles")]
    public string? Vehicles { get; set; }
}
