/**
 * SpeciesCollection automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;
namespace SdkFabric.Starwars;
public class SpeciesCollection : Collection
{
    [JsonPropertyName("results")]
    public System.Collections.Generic.List<Species>? Results { get; set; }
}
