/**
 * SpecieCollection automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;
namespace SdkFabric.Starwars;
public class SpecieCollection : Collection
{
    [JsonPropertyName("results")]
    public List<Specie>? Results { get; set; }
}
